
services:
  ubuntu:
    image: graygray/aicamera_plus_box
    container_name: aicamera_plus_box
    stdin_open: true  # Keep the container running and open for interactive mode
    tty: true  # Allocate a pseudo-TTY (useful for running bash)
    command: /bin/bash  # Run bash as the command
    privileged: true
#    user: root
    restart: always
    ports:
      - '54322:22'
    environment:
      - TZ=Asia/Taipei
    #   - JAVA_OPTS="-Dhudson.security.HudsonPrivateSecurityRealm.ID_REGEX=[a-zA-Z0-9_.@-]+"
    #   - TMP=/var/jenkins_home/tmp
    #   - TEMP=/var/jenkins_home/tmp
    #   - TMPDIR=/var/jenkins_home/tmp
    volumes:
      - /mnt/disk2/yocto_build_folder/docker:/tmp
      - /mnt/disk2/FTP/Public/Jenkins/:/ftp

#volumes:
#  vHome:
